[project]
name = "genie-graph-ad"
version = "0.1.0"
description = "Graph-based anomaly detection for jets"
requires-python = ">=3.12"
dependencies = [
    "awkward==2.14.0",
    "fastjet==3.5.1.5",
    "matplotlib==3.11.1",
    "numpy==2.4.6",
    "pandas==3.0.3",
    "scikit-learn==1.8.0",
    "scipy==1.18.1",
    "tables==3.11.1",
    "torch==2.10.0",
    "torch-geometric==2.7.0",
]
